name: Run Bot

on:
  schedule:
    - cron: "*/30 * * * *"   # jalan tiap 30 menit
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil file
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install library
        run: pip install -r requirements.txt

      - name: Jalankan bot
        run: python tes.py

        env:
          TOKEN: ${{ secrets.TOKEN }}
          RUN_BOT: ${{ secrets.RUN_BOT }}
